name: overlay_tooltip
description: An overlay tooltip handler for onboarding
version: 0.2.2
homepage: https://github.com/Deuque/overlay_tooltip

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^5.7.5

dependency_overrides:
  collection: ^1.17.2
  analyzer: ^5.13.0